apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-notification
  namespace: microservicios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-notification
  template:
    metadata:
      labels:
        app: ms-notification
    spec:
      containers:
        - name: ms-notification
          image: ms-notification:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: SERVER_PORT
              value: "8085"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://notification-postgres:5432/db_notificaciones"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: notification-secrets
                  key: DB_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-secrets
                  key: DB_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "validate"
            - name: SPRING_FLYWAY_ENABLED
              value: "true"
            - name: SPRING_FLYWAY_BASELINE_ON_MIGRATE
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-notification
  namespace: microservicios
spec:
  selector:
    app: ms-notification
  ports:
    - port: 8085
      targetPort: 8085
  type: ClusterIP