CREATE TABLE IF NOT EXISTS auth_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone_number INTEGER NOT NULL UNIQUE,
    address VARCHAR(100) NOT NULL,
    address_number INTEGER NOT NULL,
    city VARCHAR(50) NOT NULL,
    country VARCHAR(50) NOT NULL,
    role VARCHAR(20) DEFAULT 'user' NOT NULL,
    enabled BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

INSERT INTO auth_users (
    name, last_name, email, password, phone_number, 
    address, address_number, city, country, role, enabled, created_at
)
VALUES (
    'felipe', 
    'salazar', 
    'felipe@duocuc.cl', 
    '$2a$10$8.27G6B5Kx.t5u7g8H9iO.eF0D2B8V8M3L0yXh7B6T8W4R1Q7Z8G.', 
    98765432, 
    'Avenida Vicuña Mackenna', 
    7500, 
    'La Florida', 
    'Chile', 
    'user',
    true, 
    CURRENT_TIMESTAMP
)
ON CONFLICT (email) DO NOTHING;