apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-bff
  namespace: microservicios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-bff
  template:
    metadata:
      labels:
        app: ms-bff
    spec:
      containers:
        - name: ms-bff
          image: ms-bff:1.0  
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:
            - name: SERVER_PORT
              value: "8084"
            
            - name: USERS_URL
              value: "http://ms-user:8081"
            - name: AUTH_URL
              value: "http://ms-auth:8083"
            - name: PETS_URL
              value: "http://ms-pet:8082"         
            - name: NOTIFICATIONS_URL
              value: "http://ms-notification:8085"   
            - name: JWK_URI
              value: "http://ms-auth:8083/.well-known/jwks.json"
            - name: ENDPOINTS_MS_AUTH
              value: "http://ms-auth:8083"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-bff
  namespace: microservicios
spec:
  selector:
    app: ms-bff
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP