INSERT INTO pet_types (name_type, breed) VALUES 
('Perro', 'Husky'),
('Perro', 'Doberman'),
('Perro', 'Pastor Alemán'),
('Perro', 'Labrador'),
('Perro', 'Cocker Spaniel'),
('Perro', 'Bulldog'),
('Perro', 'Caniche'),
('Perro', 'Beagle'),
('Perro', 'Chihuahua'),
('Perro', 'Otro'),
('Gato', 'Naranjo'),
('Gato', 'Calico'),
('Gato', 'Egipcio'),
('Gato', 'Siamés'),
('Gato', 'Persa'),
('Gato', 'Bengalí'),
('Gato', 'Ragdoll'),
('Gato', 'Otro'),
('Ave', 'Loro'),
('Ave', 'Canario'),
('Ave', 'Paloma'),
('Ave', 'Gallina'),
('Ave', 'Ganso'),
('Ave', 'Otro'),
('Otro', 'Conejo'),
('Otro', 'Hamster'),
('Otro', 'Tortuga'),
('Otro', 'Otro')

ON CONFLICT DO NOTHING;