CREATE TABLE IF NOT EXISTS pets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    age_category VARCHAR(50) NOT NULL,
    type_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    last_seen_location VARCHAR(100),
    last_seen_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    color VARCHAR(30),
    description VARCHAR(255),
    status VARCHAR(50) NOT NULL,
    
    CONSTRAINT fk_pets_pet_type FOREIGN KEY (type_id) REFERENCES pet_types(id) ON DELETE RESTRICT
);