apiVersion: v1
kind: Secret
metadata:
  name: user-secrets
  namespace: microservicios
type: Opaque
stringData:
  DB_USER: user
  DB_PASSWORD: user123
  DB_NAME: userdb
  # Cambia este valor en producción por una cadena larga y aleatoria.
  JWT_SECRET: "jwt-secret-sanos-y-salvos-2026"