version: '3.8'

services:
  db-usuarios:
    image: postgres:15-alpine
    container_name: db_ms_usuarios
    restart: always
    environment:
      POSTGRES_DB: db_usuarios
      POSTGRES_USER: felipe_admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - ./data/usuarios_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U felipe_admin -d db_usuarios"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ms-network

  ms-usuarios:
    build: .
    container_name: ms_usuarios_app
    restart: on-failure
    depends_on:
      db-usuarios:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-usuarios:5432/db_usuarios
      SPRING_DATASOURCE_USERNAME: felipe_admin
      SPRING_DATASOURCE_PASSWORD: password123
      # Forzamos el puerto 8081 también desde aquí por seguridad
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    networks:
      - ms-network

networks:
  ms-network:
    driver: bridge