spring.application.name=ms_base
server.port=8080

# NEON DB
# spring.datasource.url=jdbc:postgresql://localhost:5432/<YOUR_DATABASE_NAME>
spring.datasource.url=jdbc:postgresql://ep-proud-firefly-aqkl84f5-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_R2JwoAlkTa5m


# NEON DB
# spring.jpa.hibernate.ddl-auto=<create | create-drop | update | validate | none>
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
