# ==========================================
# Configuración de la Aplicación
# ==========================================
spring.application.name=ms_bff
server.port=8084

# ==========================================
# Endpoints de Microservicios Externos
# ==========================================
endpoints.ms-users=${USERS_URL:http://localhost:8081}
endpoints.ms-pets=${PETS_URL:http://localhost:8082}
endpoints.ms-auth=${AUTH_URL:http://localhost:8083}

# ==========================================
# Configuración de Seguridad y CORS 
# ==========================================

app.security.cors.allowed-origins=${FRONTEND_URL:http://localhost:3000}

app.security.jwt.jwk-set-uri=${AUTH_URL:http://localhost:8083}/.well-known/jwks.json