spring.application.name=ms_bff
server.port=8084

spring.security.user.name=admin
spring.security.user.password=admin123

endpoints.ms-usuarios=${USERS_URL:http://localhost:8081}
endpoints.ms-mascotas=${PETS_URL:http://localhost:8082}
endpoints.ms-auth=${AUTH_URL:http://localhost:8083}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://ms-auth:8083/.well-known/jwks.json