apiVersion: v1
kind: Secret
metadata:
  name: pets-secrets
  namespace: microservicios
type: Opaque
stringData:
  DB_USER: pets
  DB_PASSWORD: pets123
  DB_NAME: petsdb
  # Cambia este valor en producción por una cadena larga y aleatoria.
  JWT_SECRET: "jwt-secret-sanos-y-salvos-2026"